# Generated by Django 5.1.15 on 2026-05-25 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auctions', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auctions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auctionitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionitem'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['tenant', 'status'], name='auction_ite_tenant__56875d_idx'),
        ),
        migrations.AddIndex(
            model_name='auctionitem',
            index=models.Index(fields=['tenant', 'closes_at'], name='auction_ite_tenant__d36f51_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['auction', '-amount'], name='bid_auction_c36a84_idx'),
        ),
        migrations.AddIndex(
            model_name='bid',
            index=models.Index(fields=['tenant', '-placed_at'], name='bid_tenant__c81329_idx'),
        ),
    ]
